### ISSUE TITLE
auth setup

### ISSUE THREAD

**Issue by persianphilosopher** [oschettler/knowfox#1]
This looks like a fantastic project, very much in line with the kind of thing I have been looking for.

I have been trying for a day or so to set it up as a self-hosted service but I am hitting a wall no matter which setting I tweak.  In the env file, mailtrap.io is prefilled and I had seen you [recommend it here](https://github.com/oschettler/knowfox/wiki/How-to-install-Knowfox-at-Uberspace).  In the config file, however, I see that [mailgun is prefilled](https://github.com/oschettler/knowfox/blob/098d7b5370f64da1d280446e9a09d344f33f7f6b/config/mail.php#L32)

I tried to setup gmail but have not succeeded. 

I am wondering if there is anyway to disable user authentication. I am happy to keep tweaking settings until I figure out authentication but - more importantly - I would like to really see the service in use on my server and see if it fits my workflow.

Thank you for your attention and all your work

**Comment by oschettler** [comment]
Hi, thank you for your kind words :)

Mail setup currently is overly important because of the password-less login. I will try to make this optional and start with the standard Laravel authentication setup. 

Unfortunately, I will hardly have time this week to focus on this, so, please be patient.

**Comment by persianphilosopher** [comment]
Of course, I understand the importance of the password-less login and - more to the point - I absolutely respect your schedule for something like this. Take all your time. If and when that happens, I will be happy to work on it.

**Comment by oschettler** [comment]
Hi, I have looked into the mail setup again. I haven't changed the software in any way, but rather have tried using GMail. 

I found [this question on StackOverflow](http://stackoverflow.com/questions/32515245/how-to-to-send-mail-using-gmail-in-laravel-5-1). The answers explain that Google basically blocks access from "less secure apps". I have tried this myself, but couldn't get it to work either.  However, please try this; some users on this StackOverflow thread report success.

If you could not get this to work, may I suggest you try **mailtrap** as I have [explained elsewhere](https://github.com/oschettler/knowfox/wiki/How-to-install-Knowfox-at-Uberspace). For me, this was the easiest to set up. Plus, it is just used for sending from your PHP app and does not affect your GMail account in any way. 

You also mentioned that _mailgun_ is prefilled in the config file. This is just the Laravel default which gets overridden by the .env file.

**Comment by persianphilosopher** [comment]
Thank you for your help
