### ISSUE TITLE
Bugsnag usage is problematic

### ISSUE THREAD

**Issue by dakira** [oschettler/knowfox#17]
On a fresh install a user usually doesn't have a bugsnag account. Yet the ApplicationServiceProvider binds the default logging interface to bugsnag, even if it's not available. At the very least local logging shouldn't be disabled by using bugsnag.multi:

    $this->app->alias('bugsnag.multi', \Illuminate\Contracts\Logging\Log::class);
    $this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);

With Laravel 5.6 this can of course be handled better.

**Comment by oschettler** [comment]
Good point. I didn't even know about this option. Thank you.
