### ISSUE TITLE
concord/concordUtils.js 403 - forbidden error

### ISSUE THREAD

**Issue by nicogee** [oschettler/knowfox#2]
I installed knowfox on Uberspace. When I switch to outline view, I only see a white square. The console output says concord/concordUtils.js, and status is 403 - Forbidden.

It also says the following: You are running Vue in development mode[...]

**Comment by oschettler** [comment]
I have replaced the concord library with [jqTree](https://github.com/mbraak/jqTree). Concord shouldn't cause problems any more. Also, no more messages about dev mode in Vue.
