### ISSUE TITLE
Bookmarklet default URL

### ISSUE THREAD

**Issue by nicogee** [oschettler/knowfox#3]
The bookmarklet has the default URL https://knowfox.com, which is obviously different in my case. 

After changing it to my URL (without https) it shows the save dialog for a short time, but then gives a "Whoops, looks like something went wrong." notice.

**Comment by oschettler** [comment]
Hi :)
Please set 
````
APP_DEBUG=true
````
... in your `.env` file and check what the error message says.

**Comment by nicogee** [comment]
The message:

ServerException in RequestException.php line 111:
Server error: `GET https://mercury.postlight.com/parser?url=http%3A%2F%2Fgraff.cc%2F` resulted in a `500 Internal Server Error` response:
{"message":null}

Do you need the complete stack trace?

**Comment by oschettler** [comment]
Ah! An omission on my side. I use a third party service to extract the text and metadata while bookmarking. For this to work, you need to create yourself a free account at https://mercury.postlight.com/web-parser/ and place their key as 

````
MERCURY_KEY=123412341234
````

... into your `.env` file.

**Comment by robertgarrigos** [comment]
I believe this is not working anymore with the postlight web site. I cannot see anyway to create a free account with them. Does, the hosted solution, have the avility to work with knowfox?
