### ISSUE TITLE
journal entry

### ISSUE THREAD

**Issue by 4asifm** [oschettler/knowfox#37]
Great project. 
I am looking for a personal knowledge management software (of course, open source - so that I can fiddle around when i have time) - which will let me manage information .
I wandered around through a couple of project before I stumbled upon this one
- DeepMehta (Connected Desktop) - great concept
- CherryTree ( great - but features like relationships, web snippet etc are missing)
- Joplin ( great )
I am leaving out commercial products which are awesome too - Evernote, Mindmapper
I like Knowfox - because it solves most of my needs.

I am having an issue to make a journal entry. When I click on the date on the top-menu I get this message -> "No "Journal" root". What does this mean? Should i fix it? OR leave it alone
See image
![no-journal-root](https://user-images.githubusercontent.com/7342520/79074279-81669880-7cb9-11ea-80b8-973d206ac34b.PNG)

**Comment by oschettler** [comment]
Hi,

thank you for trying Knowfox. To fix this issue, you simply have to create a toplevel entry "Journal". All yournal entries are created as children of it. It seems this is not created automatically for new users.

-- Olav

**Comment by 4asifm** [comment]
Thanks, Olav.
I created an "concept" entry of type journal called "Journal". That seems to have addressed this issue.

I will fiddle along some more - it looks to have a lot of potential.

Btw, would you know why the firefox extension has "500 Error". Do I need to enable the extension somehow? Firefox version 75.0 (64-Bit)
![firefox](https://user-images.githubusercontent.com/7342520/79081457-96f4b600-7ceb-11ea-83bb-47b5b6b700a2.png)

**Comment by oschettler** [comment]
Hi again,

this is obviously not very user friendly, but the server address is currently hard-wired in https://github.com/knowfox/firefox-extension/blob/master/popup.js#L18
To use the extension with your local installation, you will need to point this address to your server.

-- Olav

**Comment by oschettler** [comment]
I have stopped using and supporting the extension. Rather, I use Pocket to collect bookmarks and have written an adapter for it.
