### ISSUE TITLE
[Help] Please provide an example on how to create typed relationships

### ISSUE THREAD

**Issue by navigator8** [oschettler/knowfox#5]
I cannot get that to work

**Comment by oschettler** [comment]
Hi Farayi,
thank you for your question and apologies. I am aware that this part of the user interface is very under developed. Here is an example:

I want to represent the following relationships 

_Steve Blank_ 
* is teacher of _Eric Ries_
* has written _The Four Steps to the Epiphany_
* has written _The Startup Owner's Manual: ..._

I have these concepts:

* #21 -  / People / Blank, Steve
* #20 - / People / Ries, Eric
* #4213 - / Books /  __Nonfiction / The Four Steps to the Epiphany
* #3995 - / Books /  __Nonfiction / The Startup Owner's Manual: ...

At concept #21 (Steve Blank I have the following relationships:

![relationships](https://user-images.githubusercontent.com/124634/28676884-32020592-72ec-11e7-92a8-baa0d343eecb.png)

That is, relationships are represented by a YAML object, where each field is of the format

````
<target-id>: { type: <relationship-type> }
````

`<relationship-type>` is just a string. However, if you have an entry in your toplevel "Configuration" concept for this relationship type, then you can have distinct titles for the forward and backward name. The format in "Configuration" is 

![configuration](https://user-images.githubusercontent.com/124634/28677091-c76d7a6c-72ec-11e7-9f66-40e90afc3277.png)

For example, for the relationship type _written_ I have the entry 

````
written: [ 'hat geschrieben', 'geschrieben von' ]
````

... in German. In English this would be "has written" and "written by".

The result is, for my example, links on both sides of the relationship:

![at-steveblank](https://user-images.githubusercontent.com/124634/28677236-2bf9bca2-72ed-11e7-9bd1-694c0f21c461.png)

![at-ericries](https://user-images.githubusercontent.com/124634/28677264-3eca90c2-72ed-11e7-9de9-8267d330a11d.png)

Does that answer your question?

**Comment by navigator8** [comment]
This great. Thanks for taking the to explain in detail. I have been looking for something like this a long time. I have a few ideas which I want to pick your brain on over the next few weeks. What is best way of chatting?

**Comment by navigator8** [comment]
Hello again,

I have just tried the relationship with Yaml. This worked well but there appears to be bug . When I save it says "oops something went wrong". However when I go back to record - it does save the settings.

**Comment by navigator8** [comment]
Hi Olav,

Am enjoying knowfox. However, I struggle with how other functions work like Tasks. I also do realise that you do not have the bandwidth to respond to every of our questions on github. Are you able to publish a sample database with lot of examples. This will enable us to learn by example if there is no documentation on how to do certain operations.

Best regards,

________________________________

**Comment by oschettler** [comment]
Hi Farayi,

this is a very good idea. I will do this.

Best,
-- Olav
