### ISSUE TITLE
[Error] Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by navigator8** [oschettler/knowfox#6]
This error occurs under the following use cases:
1. Edit Concept
2. Change the  any of the fields under the bottom tabs
3. Press [Save Changes]

Result:

Whoops, looks like something went wrong.

**Comment by nhau** [comment]
Whoops, looks like something went wrong.

This error keeps coming after most operation on th web. Kindly give this attention

**Comment by oschettler** [comment]
With today's upgrade to Laravel 5.5, I have also added some better error handling. 

Could you please, when it happens again, note the time here so I can drill down into the logs. 

Thank you. 
-- Olav

**Comment by nhau** [comment]
Here is some error log time: 11:380pm NZ Time. You can reproduce this error by creating a concept  and save. Open concept and edit and then try to save. It will come up with this new error: This page isn’t working

knowfox.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by oschettler** [comment]
I believe that I had an inconsistant composer.lock at that time.
Closed as "can't reproduce". 

Please reopen if problem occurs again.
