### ISSUE TITLE
[Feature Request] Add Tag Cloud or Tag Page

### ISSUE THREAD

**Issue by navigator8** [oschettler/knowfox#7]
Currently it is difficult to discover them

**Comment by oschettler** [comment]
I have added a new page which lists all tags by count.

<img width="389" alt="tagcloud" src="https://user-images.githubusercontent.com/124634/31309548-32968882-ab88-11e7-9972-080ee42ac869.png">

This page will want some sort options and maybe I'll add a tag cloud for the sidebar, but there are the tags.

**Comment by navigator8** [comment]
This is a life saver for discoverability.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by oschettler** [comment]
Nice. I have now restricted the tags on this page by the current user. There is also a [brief blog article](https://blog.knowfox.com/tagging/) about tagging.
