### ISSUE TITLE
[Feature Request] Show Concept ID on the Note for easier linking rather than on address bar

### ISSUE THREAD

**Issue by navigator8** [oschettler/knowfox#8]
[Feature Request] Show Concept ID on the Note for easier linking rather than on address bar

**Comment by oschettler** [comment]
There you have it.

before

<img width="618" alt="before" src="https://user-images.githubusercontent.com/124634/31309186-60e93db6-ab82-11e7-8552-86ede412c823.png">

after

<img width="621" alt="after" src="https://user-images.githubusercontent.com/124634/31309195-8ad5df9e-ab82-11e7-80dc-5b0b95f4416a.png">

**Comment by navigator8** [comment]
Thank you. This will help with linking concepts.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
