### ISSUE TITLE
[Help] How do you use tasks?

### ISSUE THREAD

**Issue by navigator8** [oschettler/knowfox#9]

**Comment by oschettler** [comment]
Hi Farayi,

I have written a [blog entry](https://blog.knowfox.com/todo-items/) about tasks. Does that help you to get started with tasks?

-- Olav

**Comment by navigator8** [comment]
Hi Olav,

This is great! My question is answered. I will start using this feature.

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________
